POST http://127.0.0.1:8000/bank/transactions/payment/ HTTP/1.1
Content-Type: application/json
X-CSRFToken: irVx9Wz9BarmiiUAAcp1R2u0xLqwAOh5

{
    "amount": "11",
    "idempotency_key": "2532eec8-a4aa-4756-b38d-08f1f04b9578"
}
