POST http://127.0.0.1:8000/bank/transactions/transfer/ HTTP/1.1
Content-Type: application/json
X-CSRFToken: irVx9Wz9BarmiiUAAcp1R2u0xLqwAOh5

{
    "recipient_account": "1053570",
    "amount": "42.45",
    "idempotency_key": "a345d605-3cb0-4ce5-987c-166a7a0dbc19"
}
