POST http://127.0.0.1:8000/bank/transactions/withdraw/ HTTP/1.1
Content-Type: application/json
X-CSRFToken: irVx9Wz9BarmiiUAAcp1R2u0xLqwAOh5

{
    "amount": "41.32",
    "idempotency_key": "71281e65-2006-408d-949c-3e19352b06d3"
}
